### ISSUE TITLE
Prediction of PSWMs

### ISSUE THREAD

**Issue by pgonzale60** [OrensteinLab/DeepZF#1]
Hello,

Is there a wrapper where all the input is a protein sequence and the output is the PSWM for each of the zinc-finger domains found?

Best,
Pablo

P.S. Please add a link to your publication: [10.1093/bioinformatics/btac469](https://doi.org/10.1093/bioinformatics/btac469)

**Comment by OrensteinLab** [comment]
Hey Pablo,

Thanks for your interest. There is no wrapper at the current moment. You have to identify the zinc fingers by yourself according to the regular expression. Then, you can run BindZFpredictor on the identified fingers using our trained model to obtain their DNA-binding probabilities. On the set of fingers above a certain threshold (e.g. 0.5) you can then run PWMpredictor to obtain a 3-long PWM for each binding finger.

We updated the README with a link to our publication.

Thanks again,
Yaron

**Comment by pgonzale60** [comment]
Hey Yaron,

I'm an outsider in ZF binding predictions and was looking for something easy to use. 
I've enjoyed [ZF Princeton](http://zf.princeton.edu/logoMain.php), but I've seen great sequence variation depending on the input parameters. So I was looking for a better algorithm with an equally user friendly interface.

Thank you for the clarification and updating the README.

Best wishes,
Pablo
